version: '3'
  strider:
    container_name: strider
    image: strider
    build:
      context: .
    environment:
      - KPREGISTRY_URL=${KPREGISTRY_URL}
      - BIOLINK_URL=${BIOLINK_URL}
      - OMNICORP_URL=${OMNICORP_URL}
    volumes:
      - ./logs:/home/murphy/logs
    ports:
      - '5781:5781'