FROM python:3.9

# Add image info
LABEL org.opencontainers.image.source https://github.com/ranking-agent/strider

# set up requirements
WORKDIR /app

# Normal requirements
ADD requirements-lock.txt .
RUN pip install -r requirements-lock.txt

# Test requirements
ADD requirements-test-lock.txt .
RUN pip install -r requirements-test-lock.txt

# Copy in files
ADD . .

# set up default command
CMD pytest
