FROM python:3.9

# Add image info
LABEL org.opencontainers.image.source https://github.com/ranking-agent/strider

# Install pipenv
RUN pip install pipenv

# Create working directory
WORKDIR /app

# Install dependencies (including dev)
ADD Pipfile* .
RUN pipenv install --dev --system

# Copy in files
ADD . .

# set up default command
CMD pytest
