version: '3'

services:
  # Run our own kp-registry
  kp-registry:
    image: ghcr.io/ranking-agent/kp-registry:v2.2.0
    volumes:
      - ./data:/app/data
    ports:
      - '4983:4983'
  # Set up reloading using volume mounts
  strider:
    volumes:
      - ./:/app
    command: --bind 0.0.0.0:5781 --reload
    environment:
      KPREGISTRY_URL: http://kp-registry:4983
  # Redis debugging UI 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
