version: '3'

services:
  kp-registry:
    ports:
      - '4983:4983'
  strider:
    volumes:
      - ./:/home/murphy
    command: uvicorn strider.server:APP --host 0.0.0.0 --port 5781 --reload
    environment:
      STORE_RESULTS_FOR: 60
  # Redis debugging UI 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
