contact:
  email: patrick@covar.com
  name: Patrick Wang
  x-id: 'https://github.com/patrickkwang'
  x-role: responsible developer
description: Translator Autonomous Relay Agent
termsOfService: 'http://robokop.renci.org:7055/tos?service_long=Strider&provider_long=the%20Renaissance%20Computing%20Institute&provider_short=RENCI'
title: Strider
version: '1.0.0'
x-translator:
  component: ARA
  team:
  - Ranking Agent
x-trapi:
  externalDocs:
    description: |
      The values for version are restricted according to the regex in this external JSON schema. See schema and examples at url
    url: https://github.com/NCATSTranslator/translator_extensions/blob/production/x-trapi/
  operations:
   - lookup
   - filter_results_top_n
  version: 1.1.0
